@host=http://localhost:4004
@auth=Basic c3VzaGFudDoxMjM0

### EMPLOYEES

GET {{host}}/odata/v4/leave/Employees
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/Employees?$filter=employeeId eq 'EMP001'
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/Employees?$orderby=name
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/Employees?$filter=department eq 'IT'
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/Employees?$top=1
Authorization: {{auth}}

### LEAVE REQUESTS

POST {{host}}/odata/v4/leave/LeaveRequests
Authorization: {{auth}}
Content-Type: application/json

{
  "employee_ID": "4b5344ad-a792-4922-a6d4-66d17e7afefd",
  "startDate": "2026-06-10",
  "endDate": "2026-06-12",
  "reason": "Medical Leave"
}

###

POST {{host}}/odata/v4/leave/LeaveRequests
Authorization: {{auth}}
Content-Type: application/json

{
  "employee_ID": "<EMPLOYEE_UUID>",
  "startDate": "2026-06-20",
  "endDate": "2026-06-10",
  "reason": "Invalid Date Test"
}

###

GET {{host}}/odata/v4/leave/LeaveRequests
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/LeaveRequests?$filter=status eq 'Pending'
Authorization: {{auth}}

### HOLIDAYS

GET {{host}}/odata/v4/leave/Holidays
Authorization: {{auth}}

### FUNCTION : checkHoliday

GET {{host}}/odata/v4/leave/checkHoliday(date=2026-01-01)
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/checkHoliday(date=2026-06-10)
Authorization: {{auth}}

### FUNCTION : getWeather

GET {{host}}/odata/v4/leave/getWeather(city='Bangalore')
Authorization: {{auth}}

###

GET {{host}}/odata/v4/leave/getWeather(city='Mumbai')
Authorization: {{auth}}

### ACTION : approveLeave

POST {{host}}/odata/v4/leave/approveLeave
Authorization: {{auth}}
Content-Type: application/json

{
  "ID": "c5b7c7bb-c9ef-4480-a9fe-ae6e4139d297"
}

###

POST {{host}}/odata/v4/leave/approveLeave
Authorization: {{auth}}
Content-Type: application/json

{
  "ID": "<LEAVE_REQUEST_UUID>"
}

###

POST {{host}}/odata/v4/leave/approveLeave
Authorization: {{auth}}
Content-Type: application/json

{
  "ID": "c5b7c7bb-c9ef-4480-a9fe-ae6e4139d297"
}

### METADATA

GET {{host}}/odata/v4/leave/$metadata
Authorization: {{auth}}

### SWAGGER

GET {{host}}/api-docs