POST https://fda6541ftrial-dev-leave-approuter.cfapps.ap21.hana.ondemand.com/odata/v4/manager/approveLeave
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "ID": "11111111-1111-1111-1111-111111111111"
}